import type { Metadata } from "next";
import "./globals.css";
import { Bricolage } from "../utils/fonts";
import { ReactNode, FC, JSX } from "react";

export const metadata: Metadata = {
  title: "Turbo Next App",
  icons: {
    icon: "/turborepo-dark.svg",
  },
  description: "Generated by create next app",
  keywords: [
    "Abdullah Mukri",
    "Software Engineer",
    "Software Developer",
    "Fullstack Developer",
    "Portfolio Website",
    "Javascript",
    "Typescript",
    "React js",
    "Node js",
    "Next js",
  ],
  authors: {
    url: "https://github.com/abhub23",
    name: "Abdullah Mukri",
  },
  publisher: "Abdullah Mukri",
  twitter: {
    site: "https://x.com/abdullah_twt23",
    siteId: "https://x.com/abdullah_twt23",
  },

  // appLinks: {
  //   web: {
  //     url: new URL(''),
  //   },
  // },

  category: "Portfolio Website",
};

type Childtype = {
  children: ReactNode;
};
const RootLayoutReact: FC<Childtype> = ({ children }): JSX.Element => {
  return (
    <html lang="en">
      <body className={`${Bricolage}`}>{children}</body>
    </html>
  );
};
export default RootLayoutReact;
